### ISSUE TITLE
怎么设置横向

### ISSUE THREAD

**Issue by songzhiming** [szk-atmosphere/SACollectionViewVerticalScalingFlowLayout#2]
麻烦问下怎么设置横向滑动

**Comment by marty-suzuki** [comment]
Thanks for your question.

This is "vertical scaling flow layout", therefore it does not support horizontal scaling officially.
If you want to use horizontal scaling, it might be effective way that rotate `UICollectionView` 90 degrees to use `CGAffinetransform`.

Please try it.

**Comment by marty-suzuki** [comment]
@songzhiming 
I have supported horizontal mode at #5.
Please try version 2.1.0!

**Comment by songzhiming** [comment]
ok,3Q
